version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - ./volumes/otel/otel-collector.yml:/etc/otel-collector-config.yml
      - ./volumes/otel/data:/data/otel_logs # Mount local directory for logs
    ports:
      - '4317:4317' # gRPC port for OTLP
      - '55680:55680' # HTTP port for OTLP
      - '8888:8888' # Debugging port
      - '55679:55679' # ZPage Extension
    environment:
      - AWS_REGION=local
      - AWS_ACCESS_KEY_ID=625729a08b95bf1b7ff351a663f3a23c
      - AWS_SECRET_ACCESS_KEY=850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907
      - COLLECTOR_GATEWAY_ENDPOINT=localhost:4317

volumes:
  otel_data:
    driver: local # This tells Docker to use a local volume
