receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55680
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:
    endpoint: '${COLLECTOR_GATEWAY_ENDPOINT}'
    tls:
      insecure: true
  awss3:
    s3uploader:
      region: 'local'
      s3_bucket: 'test'
      s3_prefix: 'metric'
      s3_partition: 'minute'
      endpoint: 'http://storage:5000/s3'
      disable_ssl: true
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
    use_internal_logger: false
  file:
    path: /data/otel_logs/collector.txt # Store logs in the mounted volume
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4&async_insert=1
    ttl: 72h
    traces_table_name: otel_traces
    logs_table_name: otel_logs
    create_schema: true
    timeout: 5s
    database: default
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

processors:
  batch:
    timeout: 5s
    send_batch_size: 5000

extensions:
  zpages:
    endpoint: :55679
  health_check:
    endpoint: :13133

service:
  extensions: [zpages, health_check]
  telemetry:
    logs:
      level: 'debug'
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [
          # awss3,
          # otlp,
          debug,
          file,
          clickhouse,
        ]
    traces:
      receivers: [otlp]
      exporters: [
          # awss3,
          # otlp,
          debug,
          file,
          clickhouse,
        ]
    metrics:
      receivers: [otlp]
      exporters: [
          # awss3,
          otlp,
          file,
          # debug,
          clickhouse,
        ]
